/**
 * Author:  brijeshdhaker
 * Created: Sep 03, 2021
 */

insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1001, 'Desktop', 'SR-1001', 'ACTIVE', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1002, 'Phone', 'SR-1002', 'ACTIVE', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1003, 'Head Phone', 'SR-1003', 'ACTIVE', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1004, 'Laptop', 'SR-1004', 'ACTIVE', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1005, 'Desktop', 'SR-1001', 'ACTIVE', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1006, 'Phone', 'SR-1002', 'ACTIVE', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1007, 'Desktop', 'SR-1007', 'ACTIVE', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


insert into ASSETS (ASSETS_ID, ASSETS_NAME, SERIAL_NO, STATUS, USERID, ADD_TS, UPD_TS ) values
(1008, 'Laptop', 'SR-1008', 'ACTIVE', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());