#
# Application Profiles.
# 
---
#
server:
  port: 8099
spring:
  application:
    name: auditlog-service
    dummy:
      type: web
  devtools:
    add-properties: false
  #
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      use-new-id-gnerator-mappings: false
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  #
  datasource:
    name: AUDIT
    username: sa
    password:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:AUDIT
  #  url: jdbc:h2:file:/apps/hostpath/databases/AUDIT;AUTO_SERVER=true;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  #
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.yml
    contexts: h2
    parameters:
      textColumnType: TEXT
#
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      stream:
        enabled: true
    info:
      enabled: true
#      
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
#
logging:
  config: classpath:spring-logback.xml
  level:
    root: info
topic:
  name: auditlog-topic-avro
  partitions-num: 1
  replication-factor: 1
#
---
#
# local profile
#
---
#
spring:
  config:
    activate:
      on-profile: local
  #
  cloud:
    stream:
      function:
        definition: l_consumer;l_supplier;
      bindings:
        l_consumer-in-0:
          destination: auditlog-topic-avro
          group: auditlog-cgroup
          content-type: application/*+avro
          consumer:
            useNativeDecoding: true
        l_supplier-out-0:
          destination: auditlog-topic-avro
          content-type: application/*+avro
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          brokers: kafka-broker:9092
          zkNodes: zookeeper:2181
          producer-properties:
            interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://schema-registry:8081
          consumer-properties:
            interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://schema-registry:8081
            specific.avro.reader: true
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

#
---
#
#
spring:
  config:
    activate:
      on-profile: docker
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka
    instance:
    preferIpAddress: true
#
  cloud:
    stream:
      function:
        definition: l_consumer;l_supplier;
      bindings:
        l_consumer-in-0:
          destination: auditlog-topic-avro
          group: audit-cgroup
          content-type: application/*+avro
          consumer:
            useNativeDecoding: true
        l_supplier-out-0:
          destination: auditlog-topic-avro
          content-type: application/*+avro
          producer:
            useNativeDecoding: true
      kafka:
        binder:
          brokers: broker:19092
          zkNodes: zookeeper:2181
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://schema-registry:8081
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://schema-registry:8081
            specific.avro.reader: true
#

#
---
#