## YAML Template.
---
databaseChangeLog:
  - property:
      name: clob.type
      value: clob
      dbms: h2,oracle,postgresql
  - property:
      name: clob.type
      value: longtext
      dbms: mysql
  - property:
      name: boolean.type
      value: number(1)
      dbms: h2,oracle
  - property:
      name: boolean.type
      value: number(1)
      dbms: mysql
  - property:
      name: varchar.type
      value: TEXT
      dbms: h2,oracle      
  - property:
      name: varchar.type
      value: VARCHAR(250)
      dbms: mysql            