#
# Application Profiles.
# 
---
#
server:
  port: 8100
spring:
  application:
    name: gateway-service
#
  liquibase:
    enabled: false
#
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
          - Path=/api/user/**
        - id: auditlog-service-route
          uri: lb://AUDITLOG-SERVICE
          predicates:
          - Path=/api/audit/**
#
management:
  endpoints:
    web:
      exposure:
        include: "*"
#
logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
#
---
#
# local profile
#
---
#
spring:
  profiles: local  
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
#
---
#
# docker profile
#
---
#
spring:
  profiles: docker  
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka
    instance:
    preferIpAddress: true
#
