#
#
version: '3.1'
#
services:
#
  user-service:
    image: brijeshdhaker/user-service:0.0.1-SNAPSHOT
    container_name: user-service
    ports:
      - 8094:8094

#
  auditlog-service:
    image: brijeshdhaker/auditlog-service:0.0.1-SNAPSHOT
    container_name: auditlog-service
    ports:
      - 8099:8099

  #
  eureka-discovery-service:
    image: brijeshdhaker/eureka-discovery-service:0.0.1-SNAPSHOT
    container_name: eureka-discovery-service
    ports:
      - 8761:8761

  #
  gateway-service:
    image: brijeshdhaker/gateway-service:0.0.1-SNAPSHOT
    container_name: gateway-service
    ports:
      - 8100:8100

#
#networks:
#  default:
#    external:
#      name: bridge  
#  backend:
#    driver: bridge
# 