apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: app-springboot
  name: app-springboot
  namespace: i100121
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: app-springboot
  type: NodePort
status:
  loadBalancer: {}
