apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app-springboot
  name: app-springboot
  namespace: i100121
spec:
  volumes:
    - name: app-vol
      hostPath: 
        path: /d/hostpath
        type: Directory
  containers:
  - image: brijeshdhaker/my-app:0.0.1-SNAPSHOT
    name: c1
    volumeMounts:
      - name: app-vol
        mountPath: /d/hostpath
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# 
# kubectl run app-springboot --image=brijeshdhaker/my-app:0.0.1-SNAPSHOT -n i100121 --port=8080 $do > app-springboot.yaml
# kubectl expose pod app-springboot -n i100121 --port=80 --target-port=8080 --type=NodePort $do > app-svc.yaml
#