apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name : app-pvc
  namespace: i100121
  labels:
    app: app-springboot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  
