apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
  namespace: i100121
  labels:
    app: app-springboot
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /d/hostpath
